[workspace]
members = [
    "shawncore-pq-crypto",
    "shawncore-rtos-sync",
    "shawncore-ffi",
    "benchmarks",
    "validation"
]
exclude = ["fuzz"]
resolver = "2"

[workspace.package]
license-file = "LICENSE"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = "fat"
codegen-units = 1
strip = "symbols"
